// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mmo {

  /// <summary>Holder for reflection information generated from entity.proto</summary>
  public static partial class EntityReflection {

    #region Descriptor
    /// <summary>File descriptor for entity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxlbnRpdHkucHJvdG8SA21tbxoMY29tbW9uLnByb3RvIvsCCg5FbnRpdHlT",
            "bmFwc2hvdBIRCgllbnRpdHlfaWQYASABKA0SEwoLZW50aXR5X3R5cGUYAiAB",
            "KA0SCwoDdWlkGAMgASgJEhIKCm1vZGVsX3R5cGUYBCABKA0SEwoLYXRrX3Ry",
            "aWdnZXIYBSABKA0SHgoIcG9zaXRpb24YBiABKAsyDC5tbW8uVmVjdG9yMxIN",
            "CgVyb3RfeRgHIAEoAhIKCgJocBgIIAEoBRIOCgZtYXhfaHAYCSABKAUSEgoK",
            "YW5pbV9zdGF0ZRgKIAEoDRIQCghndWlsZF9pZBgOIAEoCRIVCg1za2lsbF90",
            "cmlnZ2VyGAsgASgNEhAKCHNraWxsX2lkGAwgASgJEiIKDHNraWxsX3Rhcmdl",
            "dBgNIAEoCzIMLm1tby5WZWN0b3IzEhQKDGlzX2Nyb3VjaGluZxgPIAEoCBIS",
            "Cgppc19qdW1waW5nGBAgASgIEhIKCmlzX3JvbGxpbmcYESABKAgSDwoHaXNf",
            "ZGVhZBgSIAEoCCJRCg5QbGF5ZXJTbmFwc2hvdBIYChBwbGF5ZXJfZW50aXR5",
            "X2lkGAEgASgNEiUKCGVudGl0aWVzGAIgAygLMhMubW1vLkVudGl0eVNuYXBz",
            "aG90YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mmo.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mmo.EntitySnapshot), global::Mmo.EntitySnapshot.Parser, new[]{ "EntityId", "EntityType", "Uid", "ModelType", "AtkTrigger", "Position", "RotY", "Hp", "MaxHp", "AnimState", "GuildId", "SkillTrigger", "SkillId", "SkillTarget", "IsCrouching", "IsJumping", "IsRolling", "IsDead" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mmo.PlayerSnapshot), global::Mmo.PlayerSnapshot.Parser, new[]{ "PlayerEntityId", "Entities" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 单个实体状态 (怪物/玩家)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntitySnapshot : pb::IMessage<EntitySnapshot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntitySnapshot> _parser = new pb::MessageParser<EntitySnapshot>(() => new EntitySnapshot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntitySnapshot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mmo.EntityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySnapshot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySnapshot(EntitySnapshot other) : this() {
      entityId_ = other.entityId_;
      entityType_ = other.entityType_;
      uid_ = other.uid_;
      modelType_ = other.modelType_;
      atkTrigger_ = other.atkTrigger_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotY_ = other.rotY_;
      hp_ = other.hp_;
      maxHp_ = other.maxHp_;
      animState_ = other.animState_;
      guildId_ = other.guildId_;
      skillTrigger_ = other.skillTrigger_;
      skillId_ = other.skillId_;
      skillTarget_ = other.skillTarget_ != null ? other.skillTarget_.Clone() : null;
      isCrouching_ = other.isCrouching_;
      isJumping_ = other.isJumping_;
      isRolling_ = other.isRolling_;
      isDead_ = other.isDead_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySnapshot Clone() {
      return new EntitySnapshot(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private uint entityId_;
    /// <summary>
    /// entityId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "entity_type" field.</summary>
    public const int EntityTypeFieldNumber = 2;
    private uint entityType_;
    /// <summary>
    /// 0=Player, 1=Monster
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EntityType {
      get { return entityType_; }
      set {
        entityType_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 3;
    private string uid_ = "";
    /// <summary>
    /// 玩家 uid (怪物为空)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model_type" field.</summary>
    public const int ModelTypeFieldNumber = 4;
    private uint modelType_;
    /// <summary>
    /// 职业 (0=嘉然 1=妮可 2=流萤 3=浮波柚叶)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ModelType {
      get { return modelType_; }
      set {
        modelType_ = value;
      }
    }

    /// <summary>Field number for the "atk_trigger" field.</summary>
    public const int AtkTriggerFieldNumber = 5;
    private uint atkTrigger_;
    /// <summary>
    /// 攻击触发器 (每次攻击 +1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AtkTrigger {
      get { return atkTrigger_; }
      set {
        atkTrigger_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 6;
    private global::Mmo.Vector3 position_;
    /// <summary>
    /// 位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mmo.Vector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rot_y" field.</summary>
    public const int RotYFieldNumber = 7;
    private float rotY_;
    /// <summary>
    /// Y 轴旋转 (度)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotY {
      get { return rotY_; }
      set {
        rotY_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 8;
    private int hp_;
    /// <summary>
    /// 当前 HP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "max_hp" field.</summary>
    public const int MaxHpFieldNumber = 9;
    private int maxHp_;
    /// <summary>
    /// 最大 HP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxHp {
      get { return maxHp_; }
      set {
        maxHp_ = value;
      }
    }

    /// <summary>Field number for the "anim_state" field.</summary>
    public const int AnimStateFieldNumber = 10;
    private uint animState_;
    /// <summary>
    /// 动画状态 (byte)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AnimState {
      get { return animState_; }
      set {
        animState_ = value;
      }
    }

    /// <summary>Field number for the "guild_id" field.</summary>
    public const int GuildIdFieldNumber = 14;
    private string guildId_ = "";
    /// <summary>
    /// 公会 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GuildId {
      get { return guildId_; }
      set {
        guildId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "skill_trigger" field.</summary>
    public const int SkillTriggerFieldNumber = 11;
    private uint skillTrigger_;
    /// <summary>
    /// 技能触发器 (每次施法 +1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SkillTrigger {
      get { return skillTrigger_; }
      set {
        skillTrigger_ = value;
      }
    }

    /// <summary>Field number for the "skill_id" field.</summary>
    public const int SkillIdFieldNumber = 12;
    private string skillId_ = "";
    /// <summary>
    /// 最后释放的技能 ID（怪物为空）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SkillId {
      get { return skillId_; }
      set {
        skillId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "skill_target" field.</summary>
    public const int SkillTargetFieldNumber = 13;
    private global::Mmo.Vector3 skillTarget_;
    /// <summary>
    /// 技能目标位置（怪物为默认）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mmo.Vector3 SkillTarget {
      get { return skillTarget_; }
      set {
        skillTarget_ = value;
      }
    }

    /// <summary>Field number for the "is_crouching" field.</summary>
    public const int IsCrouchingFieldNumber = 15;
    private bool isCrouching_;
    /// <summary>
    /// 蹲伏
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCrouching {
      get { return isCrouching_; }
      set {
        isCrouching_ = value;
      }
    }

    /// <summary>Field number for the "is_jumping" field.</summary>
    public const int IsJumpingFieldNumber = 16;
    private bool isJumping_;
    /// <summary>
    /// 跳跃
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsJumping {
      get { return isJumping_; }
      set {
        isJumping_ = value;
      }
    }

    /// <summary>Field number for the "is_rolling" field.</summary>
    public const int IsRollingFieldNumber = 17;
    private bool isRolling_;
    /// <summary>
    /// 翻滚
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRolling {
      get { return isRolling_; }
      set {
        isRolling_ = value;
      }
    }

    /// <summary>Field number for the "is_dead" field.</summary>
    public const int IsDeadFieldNumber = 18;
    private bool isDead_;
    /// <summary>
    /// 死亡
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDead {
      get { return isDead_; }
      set {
        isDead_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntitySnapshot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntitySnapshot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (EntityType != other.EntityType) return false;
      if (Uid != other.Uid) return false;
      if (ModelType != other.ModelType) return false;
      if (AtkTrigger != other.AtkTrigger) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotY, other.RotY)) return false;
      if (Hp != other.Hp) return false;
      if (MaxHp != other.MaxHp) return false;
      if (AnimState != other.AnimState) return false;
      if (GuildId != other.GuildId) return false;
      if (SkillTrigger != other.SkillTrigger) return false;
      if (SkillId != other.SkillId) return false;
      if (!object.Equals(SkillTarget, other.SkillTarget)) return false;
      if (IsCrouching != other.IsCrouching) return false;
      if (IsJumping != other.IsJumping) return false;
      if (IsRolling != other.IsRolling) return false;
      if (IsDead != other.IsDead) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (EntityType != 0) hash ^= EntityType.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (ModelType != 0) hash ^= ModelType.GetHashCode();
      if (AtkTrigger != 0) hash ^= AtkTrigger.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (RotY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotY);
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (MaxHp != 0) hash ^= MaxHp.GetHashCode();
      if (AnimState != 0) hash ^= AnimState.GetHashCode();
      if (GuildId.Length != 0) hash ^= GuildId.GetHashCode();
      if (SkillTrigger != 0) hash ^= SkillTrigger.GetHashCode();
      if (SkillId.Length != 0) hash ^= SkillId.GetHashCode();
      if (skillTarget_ != null) hash ^= SkillTarget.GetHashCode();
      if (IsCrouching != false) hash ^= IsCrouching.GetHashCode();
      if (IsJumping != false) hash ^= IsJumping.GetHashCode();
      if (IsRolling != false) hash ^= IsRolling.GetHashCode();
      if (IsDead != false) hash ^= IsDead.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(EntityId);
      }
      if (EntityType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(EntityType);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uid);
      }
      if (ModelType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ModelType);
      }
      if (AtkTrigger != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AtkTrigger);
      }
      if (position_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Position);
      }
      if (RotY != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(RotY);
      }
      if (Hp != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Hp);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MaxHp);
      }
      if (AnimState != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(AnimState);
      }
      if (SkillTrigger != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(SkillTrigger);
      }
      if (SkillId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(SkillId);
      }
      if (skillTarget_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(SkillTarget);
      }
      if (GuildId.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(GuildId);
      }
      if (IsCrouching != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsCrouching);
      }
      if (IsJumping != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsJumping);
      }
      if (IsRolling != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(IsRolling);
      }
      if (IsDead != false) {
        output.WriteRawTag(144, 1);
        output.WriteBool(IsDead);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(EntityId);
      }
      if (EntityType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(EntityType);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uid);
      }
      if (ModelType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ModelType);
      }
      if (AtkTrigger != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(AtkTrigger);
      }
      if (position_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Position);
      }
      if (RotY != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(RotY);
      }
      if (Hp != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Hp);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(MaxHp);
      }
      if (AnimState != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(AnimState);
      }
      if (SkillTrigger != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(SkillTrigger);
      }
      if (SkillId.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(SkillId);
      }
      if (skillTarget_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(SkillTarget);
      }
      if (GuildId.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(GuildId);
      }
      if (IsCrouching != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsCrouching);
      }
      if (IsJumping != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsJumping);
      }
      if (IsRolling != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(IsRolling);
      }
      if (IsDead != false) {
        output.WriteRawTag(144, 1);
        output.WriteBool(IsDead);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
      }
      if (EntityType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityType);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (ModelType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ModelType);
      }
      if (AtkTrigger != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AtkTrigger);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (RotY != 0F) {
        size += 1 + 4;
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (MaxHp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHp);
      }
      if (AnimState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AnimState);
      }
      if (GuildId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GuildId);
      }
      if (SkillTrigger != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SkillTrigger);
      }
      if (SkillId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SkillId);
      }
      if (skillTarget_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SkillTarget);
      }
      if (IsCrouching != false) {
        size += 1 + 1;
      }
      if (IsJumping != false) {
        size += 2 + 1;
      }
      if (IsRolling != false) {
        size += 2 + 1;
      }
      if (IsDead != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntitySnapshot other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.EntityType != 0) {
        EntityType = other.EntityType;
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.ModelType != 0) {
        ModelType = other.ModelType;
      }
      if (other.AtkTrigger != 0) {
        AtkTrigger = other.AtkTrigger;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Mmo.Vector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.RotY != 0F) {
        RotY = other.RotY;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      if (other.MaxHp != 0) {
        MaxHp = other.MaxHp;
      }
      if (other.AnimState != 0) {
        AnimState = other.AnimState;
      }
      if (other.GuildId.Length != 0) {
        GuildId = other.GuildId;
      }
      if (other.SkillTrigger != 0) {
        SkillTrigger = other.SkillTrigger;
      }
      if (other.SkillId.Length != 0) {
        SkillId = other.SkillId;
      }
      if (other.skillTarget_ != null) {
        if (skillTarget_ == null) {
          SkillTarget = new global::Mmo.Vector3();
        }
        SkillTarget.MergeFrom(other.SkillTarget);
      }
      if (other.IsCrouching != false) {
        IsCrouching = other.IsCrouching;
      }
      if (other.IsJumping != false) {
        IsJumping = other.IsJumping;
      }
      if (other.IsRolling != false) {
        IsRolling = other.IsRolling;
      }
      if (other.IsDead != false) {
        IsDead = other.IsDead;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 16: {
            EntityType = input.ReadUInt32();
            break;
          }
          case 26: {
            Uid = input.ReadString();
            break;
          }
          case 32: {
            ModelType = input.ReadUInt32();
            break;
          }
          case 40: {
            AtkTrigger = input.ReadUInt32();
            break;
          }
          case 50: {
            if (position_ == null) {
              Position = new global::Mmo.Vector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 61: {
            RotY = input.ReadFloat();
            break;
          }
          case 64: {
            Hp = input.ReadInt32();
            break;
          }
          case 72: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 80: {
            AnimState = input.ReadUInt32();
            break;
          }
          case 88: {
            SkillTrigger = input.ReadUInt32();
            break;
          }
          case 98: {
            SkillId = input.ReadString();
            break;
          }
          case 106: {
            if (skillTarget_ == null) {
              SkillTarget = new global::Mmo.Vector3();
            }
            input.ReadMessage(SkillTarget);
            break;
          }
          case 114: {
            GuildId = input.ReadString();
            break;
          }
          case 120: {
            IsCrouching = input.ReadBool();
            break;
          }
          case 128: {
            IsJumping = input.ReadBool();
            break;
          }
          case 136: {
            IsRolling = input.ReadBool();
            break;
          }
          case 144: {
            IsDead = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EntityId = input.ReadUInt32();
            break;
          }
          case 16: {
            EntityType = input.ReadUInt32();
            break;
          }
          case 26: {
            Uid = input.ReadString();
            break;
          }
          case 32: {
            ModelType = input.ReadUInt32();
            break;
          }
          case 40: {
            AtkTrigger = input.ReadUInt32();
            break;
          }
          case 50: {
            if (position_ == null) {
              Position = new global::Mmo.Vector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 61: {
            RotY = input.ReadFloat();
            break;
          }
          case 64: {
            Hp = input.ReadInt32();
            break;
          }
          case 72: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 80: {
            AnimState = input.ReadUInt32();
            break;
          }
          case 88: {
            SkillTrigger = input.ReadUInt32();
            break;
          }
          case 98: {
            SkillId = input.ReadString();
            break;
          }
          case 106: {
            if (skillTarget_ == null) {
              SkillTarget = new global::Mmo.Vector3();
            }
            input.ReadMessage(SkillTarget);
            break;
          }
          case 114: {
            GuildId = input.ReadString();
            break;
          }
          case 120: {
            IsCrouching = input.ReadBool();
            break;
          }
          case 128: {
            IsJumping = input.ReadBool();
            break;
          }
          case 136: {
            IsRolling = input.ReadBool();
            break;
          }
          case 144: {
            IsDead = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 玩家 AOI 快照 (包含所有可见实体)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerSnapshot : pb::IMessage<PlayerSnapshot>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerSnapshot> _parser = new pb::MessageParser<PlayerSnapshot>(() => new PlayerSnapshot());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerSnapshot> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mmo.EntityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapshot() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapshot(PlayerSnapshot other) : this() {
      playerEntityId_ = other.playerEntityId_;
      entities_ = other.entities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSnapshot Clone() {
      return new PlayerSnapshot(this);
    }

    /// <summary>Field number for the "player_entity_id" field.</summary>
    public const int PlayerEntityIdFieldNumber = 1;
    private uint playerEntityId_;
    /// <summary>
    /// 目标玩家 entityId
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PlayerEntityId {
      get { return playerEntityId_; }
      set {
        playerEntityId_ = value;
      }
    }

    /// <summary>Field number for the "entities" field.</summary>
    public const int EntitiesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Mmo.EntitySnapshot> _repeated_entities_codec
        = pb::FieldCodec.ForMessage(18, global::Mmo.EntitySnapshot.Parser);
    private readonly pbc::RepeatedField<global::Mmo.EntitySnapshot> entities_ = new pbc::RepeatedField<global::Mmo.EntitySnapshot>();
    /// <summary>
    /// 可见实体列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Mmo.EntitySnapshot> Entities {
      get { return entities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerSnapshot);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerSnapshot other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerEntityId != other.PlayerEntityId) return false;
      if(!entities_.Equals(other.entities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerEntityId != 0) hash ^= PlayerEntityId.GetHashCode();
      hash ^= entities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerEntityId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerEntityId);
      }
      entities_.WriteTo(output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerEntityId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerEntityId);
      }
      entities_.WriteTo(ref output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerEntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerEntityId);
      }
      size += entities_.CalculateSize(_repeated_entities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerSnapshot other) {
      if (other == null) {
        return;
      }
      if (other.PlayerEntityId != 0) {
        PlayerEntityId = other.PlayerEntityId;
      }
      entities_.Add(other.entities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerEntityId = input.ReadUInt32();
            break;
          }
          case 18: {
            entities_.AddEntriesFrom(input, _repeated_entities_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerEntityId = input.ReadUInt32();
            break;
          }
          case 18: {
            entities_.AddEntriesFrom(ref input, _repeated_entities_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
